import api from "../lib/Axios";

export interface ExchangeRate {
  id: string;
  rate: number;
  timestamp: string;
  base: string;
  updatedAt: string;
}

export interface Currency {
  code: string;
  name: string;
  symbol: string;
}

export interface ExchangeRatesResponse {
  currencies: Currency[];
  exchangeRates: ExchangeRate[];
}

// Currency mapping with names and symbols
const CURRENCY_INFO: Record<string, { name: string; symbol: string }> = {
  USD: { name: "US Dollar", symbol: "$" },
  EUR: { name: "Euro", symbol: "€" },
  GBP: { name: "British Pound", symbol: "£" },
  JPY: { name: "Japanese Yen", symbol: "¥" },
  AUD: { name: "Australian Dollar", symbol: "A$" },
  CAD: { name: "Canadian Dollar", symbol: "C$" },
  CHF: { name: "Swiss Franc", symbol: "Fr" },
  CNY: { name: "Chinese Yuan", symbol: "¥" },
  SEK: { name: "Swedish Krona", symbol: "kr" },
  NZD: { name: "New Zealand Dollar", symbol: "NZ$" },
  MXN: { name: "Mexican Peso", symbol: "$" },
  SGD: { name: "Singapore Dollar", symbol: "S$" },
  HKD: { name: "Hong Kong Dollar", symbol: "HK$" },
  NOK: { name: "Norwegian Krone", symbol: "kr" },
  ZAR: { name: "South African Rand", symbol: "R" },
  BRL: { name: "Brazilian Real", symbol: "R$" },
  INR: { name: "Indian Rupee", symbol: "₹" },
  KRW: { name: "South Korean Won", symbol: "₩" },
  RUB: { name: "Russian Ruble", symbol: "₽" },
  THB: { name: "Thai Baht", symbol: "฿" },
  TRY: { name: "Turkish Lira", symbol: "₺" },
  PLN: { name: "Polish Złoty", symbol: "zł" },
  CZK: { name: "Czech Koruna", symbol: "Kč" },
  DKK: { name: "Danish Krone", symbol: "kr" },
  HUF: { name: "Hungarian Forint", symbol: "Ft" },
  RON: { name: "Romanian Leu", symbol: "lei" },
  BGN: { name: "Bulgarian Lev", symbol: "лв" },
  HRK: { name: "Croatian Kuna", symbol: "kn" },
  ILS: { name: "Israeli Shekel", symbol: "₪" },
  AED: { name: "UAE Dirham", symbol: "د.إ" },
  SAR: { name: "Saudi Riyal", symbol: "﷼" },
  QAR: { name: "Qatari Riyal", symbol: "﷼" },
  KWD: { name: "Kuwaiti Dinar", symbol: "د.ك" },
  BHD: { name: "Bahraini Dinar", symbol: ".د.ب" },
  OMR: { name: "Omani Rial", symbol: "﷼" },
  JOD: { name: "Jordanian Dinar", symbol: "د.ا" },
  LBP: { name: "Lebanese Pound", symbol: "ل.ل" },
  EGP: { name: "Egyptian Pound", symbol: "£" },
  MAD: { name: "Moroccan Dirham", symbol: "د.م." },
  TND: { name: "Tunisian Dinar", symbol: "د.ت" },
  DZD: { name: "Algerian Dinar", symbol: "د.ج" },
  LYD: { name: "Libyan Dinar", symbol: "ل.د" },
  PHP: { name: "Philippine Peso", symbol: "₱" },
  IDR: { name: "Indonesian Rupiah", symbol: "Rp" },
  MYR: { name: "Malaysian Ringgit", symbol: "RM" },
  VND: { name: "Vietnamese Dong", symbol: "₫" },
  LAK: { name: "Lao Kip", symbol: "₭" },
  KHR: { name: "Cambodian Riel", symbol: "៛" },
  MMK: { name: "Myanmar Kyat", symbol: "K" },
  BDT: { name: "Bangladeshi Taka", symbol: "৳" },
  PKR: { name: "Pakistani Rupee", symbol: "₨" },
  LKR: { name: "Sri Lankan Rupee", symbol: "₨" },
  NPR: { name: "Nepalese Rupee", symbol: "₨" },
  AFN: { name: "Afghan Afghani", symbol: "؋" },
  IRR: { name: "Iranian Rial", symbol: "﷼" },
  IQD: { name: "Iraqi Dinar", symbol: "ع.د" },
  SYP: { name: "Syrian Pound", symbol: "£" },
  YER: { name: "Yemeni Rial", symbol: "﷼" },
  ETB: { name: "Ethiopian Birr", symbol: "Br" },
  KES: { name: "Kenyan Shilling", symbol: "KSh" },
  UGX: { name: "Ugandan Shilling", symbol: "USh" },
  TZS: { name: "Tanzanian Shilling", symbol: "TSh" },
  RWF: { name: "Rwandan Franc", symbol: "Fr" },
  NGN: { name: "Nigerian Naira", symbol: "₦" },
  GHS: { name: "Ghanaian Cedi", symbol: "₵" },
  XOF: { name: "West African CFA Franc", symbol: "Fr" },
  XAF: { name: "Central African CFA Franc", symbol: "Fr" },
  CDF: { name: "Congolese Franc", symbol: "Fr" },
  MZN: { name: "Mozambican Metical", symbol: "MT" },
  ZMW: { name: "Zambian Kwacha", symbol: "ZK" },
  BWP: { name: "Botswana Pula", symbol: "P" },
  NAD: { name: "Namibian Dollar", symbol: "N$" },
  SZL: { name: "Swazi Lilangeni", symbol: "L" },
  LSL: { name: "Lesotho Loti", symbol: "L" },
  MWK: { name: "Malawian Kwacha", symbol: "MK" },
  MGA: { name: "Malagasy Ariary", symbol: "Ar" },
  MUR: { name: "Mauritian Rupee", symbol: "₨" },
  SCR: { name: "Seychellois Rupee", symbol: "₨" },
  KMF: { name: "Comorian Franc", symbol: "Fr" },
  DJF: { name: "Djiboutian Franc", symbol: "Fr" },
  SOS: { name: "Somali Shilling", symbol: "Sh" },
  ERN: { name: "Eritrean Nakfa", symbol: "Nfk" },
  SDG: { name: "Sudanese Pound", symbol: "£" },
  SSP: { name: "South Sudanese Pound", symbol: "£" },
  CLP: { name: "Chilean Peso", symbol: "$" },
  ARS: { name: "Argentine Peso", symbol: "$" },
  UYU: { name: "Uruguayan Peso", symbol: "$" },
  PYG: { name: "Paraguayan Guarani", symbol: "₲" },
  BOB: { name: "Bolivian Boliviano", symbol: "Bs" },
  PEN: { name: "Peruvian Sol", symbol: "S/" },
  COP: { name: "Colombian Peso", symbol: "$" },
  VES: { name: "Venezuelan Bolívar", symbol: "Bs" },
  GYD: { name: "Guyanese Dollar", symbol: "$" },
  SRD: { name: "Surinamese Dollar", symbol: "$" },
  TTD: { name: "Trinidad and Tobago Dollar", symbol: "$" },
  BBD: { name: "Barbadian Dollar", symbol: "$" },
  JMD: { name: "Jamaican Dollar", symbol: "$" },
  BSD: { name: "Bahamian Dollar", symbol: "$" },
  BZD: { name: "Belize Dollar", symbol: "$" },
  GTQ: { name: "Guatemalan Quetzal", symbol: "Q" },
  HNL: { name: "Honduran Lempira", symbol: "L" },
  NIO: { name: "Nicaraguan Córdoba", symbol: "C$" },
  CRC: { name: "Costa Rican Colón", symbol: "₡" },
  PAB: { name: "Panamanian Balboa", symbol: "B/." },
  DOP: { name: "Dominican Peso", symbol: "$" },
  HTG: { name: "Haitian Gourde", symbol: "G" },
  CUP: { name: "Cuban Peso", symbol: "$" },
  CUC: { name: "Cuban Convertible Peso", symbol: "$" },
  ALL: { name: "Albanian Lek", symbol: "L" },
  RSD: { name: "Serbian Dinar", symbol: "din" },
  BAM: { name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
  MKD: { name: "Macedonian Denar", symbol: "den" },
  MDL: { name: "Moldovan Leu", symbol: "L" },
  BYN: { name: "Belarusian Ruble", symbol: "Br" },
  UAH: { name: "Ukrainian Hryvnia", symbol: "₴" },
  GEL: { name: "Georgian Lari", symbol: "₾" },
  AMD: { name: "Armenian Dram", symbol: "֏" },
  AZN: { name: "Azerbaijani Manat", symbol: "₼" },
  KZT: { name: "Kazakhstani Tenge", symbol: "₸" },
  KGS: { name: "Kyrgystani Som", symbol: "с" },
  UZS: { name: "Uzbekistani Som", symbol: "сум" },
  TJS: { name: "Tajikistani Somoni", symbol: "ЅМ" },
  TMT: { name: "Turkmenistani Manat", symbol: "m" },
  MNT: { name: "Mongolian Tugrik", symbol: "₮" },
  KPW: { name: "North Korean Won", symbol: "₩" },
  BTN: { name: "Bhutanese Ngultrum", symbol: "Nu" },
  MVR: { name: "Maldivian Rufiyaa", symbol: "Rf" },
  ISK: { name: "Icelandic Króna", symbol: "kr" },
  FJD: { name: "Fijian Dollar", symbol: "$" },
  TOP: { name: "Tongan Paʻanga", symbol: "T$" },
  WST: { name: "Samoan Tala", symbol: "T" },
  VUV: { name: "Vanuatu Vatu", symbol: "Vt" },
  PGK: { name: "Papua New Guinean Kina", symbol: "K" },
  SBD: { name: "Solomon Islands Dollar", symbol: "$" },
  NCX: { name: "New Caledonian Franc", symbol: "Fr" },
  XPF: { name: "CFP Franc", symbol: "Fr" },
  TWD: { name: "Taiwan Dollar", symbol: "NT$" },
  MOP: { name: "Macanese Pataca", symbol: "P" },
  BND: { name: "Brunei Dollar", symbol: "$" },
  KYD: { name: "Cayman Islands Dollar", symbol: "$" },
  BMD: { name: "Bermudian Dollar", symbol: "$" },
  AWG: { name: "Aruban Florin", symbol: "ƒ" },
  ANG: { name: "Netherlands Antillean Guilder", symbol: "ƒ" },
  CVE: { name: "Cape Verdean Escudo", symbol: "$" },
  STN: { name: "São Tomé and Príncipe Dobra", symbol: "Db" },
  GMD: { name: "Gambian Dalasi", symbol: "D" },
  GNF: { name: "Guinean Franc", symbol: "Fr" },
  SLL: { name: "Sierra Leonean Leone", symbol: "Le" },
  LRD: { name: "Liberian Dollar", symbol: "$" },
  CIF: { name: "Ivorian Franc", symbol: "Fr" },
  BIF: { name: "Burundian Franc", symbol: "Fr" },
  XCD: { name: "East Caribbean Dollar", symbol: "$" },
  FKP: { name: "Falkland Islands Pound", symbol: "£" },
  GIP: { name: "Gibraltar Pound", symbol: "£" },
  SHP: { name: "Saint Helena Pound", symbol: "£" },
  JEP: { name: "Jersey Pound", symbol: "£" },
  GGP: { name: "Guernsey Pound", symbol: "£" },
  IMP: { name: "Isle of Man Pound", symbol: "£" },
  CLF: { name: "Chilean Unit of Account", symbol: "UF" },
  XAG: { name: "Silver Ounce", symbol: "oz" },
  XAU: { name: "Gold Ounce", symbol: "oz" },
  XPD: { name: "Palladium Ounce", symbol: "oz" },
  XPT: { name: "Platinum Ounce", symbol: "oz" },
  BTC: { name: "Bitcoin", symbol: "₿" },
  XDR: { name: "Special Drawing Rights", symbol: "SDR" },
  CNH: { name: "Chinese Yuan (Offshore)", symbol: "¥" },
  SVC: { name: "Salvadoran Colón", symbol: "₡" },
  STD: { name: "São Tomé and Príncipe Dobra (old)", symbol: "Db" },
  MRU: { name: "Mauritanian Ouguiya", symbol: "UM" },
  ZWL: { name: "Zimbabwean Dollar", symbol: "$" }
};

export const exchangeRatesRequests = {
  getExchangeRates: async (): Promise<ExchangeRatesResponse> => {
    const res = await api.get<ExchangeRate[]>('/exchange-rates');
    
    // Transform the API response to match the expected format
    const currencies: Currency[] = res.data.map(rate => ({
      code: rate.id,
      name: CURRENCY_INFO[rate.id]?.name || rate.id,
      symbol: CURRENCY_INFO[rate.id]?.symbol || rate.id
    })).sort((a, b) => a.code.localeCompare(b.code));

    return {
      currencies,
      exchangeRates: res.data
    };
  },
};
