import { ReactNode } from 'react';
import localFont from 'next/font/local';
import { ThemeProvider } from '@/context/ThemeContext';
import NavBar from '@/components/Layout/NavBar';
import Footer from '@/components/Layout/Footer';
import SideBar from '@/components/Layout/SideBar';
import QueryClientWrapper from './QueryClientWrapper';
import useAuth from './auth/useAuth';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Expense Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const isAuthenticated = useAuth(); // Get authentication status

  return (
    <ThemeProvider>
      <QueryClientWrapper>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
          >
            {/* Conditionally render NavBar, SideBar, and Footer */}
            {isAuthenticated && (
              <>
                <SideBar />
                <div className="w-full h-full">
                  <NavBar />
                  {children}
                  <Footer />
                </div>
              </>
            )}

            {/* If not authenticated (like on the login page), just show the login page content */}
            {!isAuthenticated && children}
          </body>
        </html>
      </QueryClientWrapper>
    </ThemeProvider>
  );
}
