import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import NavBar from "@/components/Layout/NavBar";
import Footer from "@/components/Layout/Footer";
import SideBar from "@/components/Layout/SideBar";
import QueryClientWrapper from "./QueryClientWrapper";
import { Toaster } from "react-hot-toast";
import { cookies } from "next/headers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Expense tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authToken = cookies().get("authToken");
  return (
    <ThemeProvider>
      <QueryClientWrapper>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
          >
            <Toaster
              position="bottom-right"
              toastOptions={{
                style: {
                  background: "var(--bg)",
                  color: "var(--text)",
                  borderRadius: "var(--border-radius)",
                  fontFamily: "var(--font)",
                },
              }}
            />
            {authToken ? ( // Only show layout if user is authenticated
              <>
                <SideBar />
                <div className="w-full h-full">
                  <NavBar />
                  {children}
                  <Footer />
                </div>
              </>
            ) : (
              <div className="w-full h-full">{children}</div> // Only show login page
            )}
          </body>
        </html>
      </QueryClientWrapper>
    </ThemeProvider>
  );
}
